export const homeData = [
  {
    id: 1,
    name: "فیلم تلماسه",
    rating: 4.7,
    time: "2hr : 22mins",
    desc: "در نیویورک سیتی خیالی، آپولو باید برای پیدا کردن همسر گمشده و پسر ربوده شده‌اش جهانی جادویی را پشت سر بگذارد و با مرگ رودررو شود. ",
    starrring: "اکبر عبدی، مهران مدیری",
    genres: "اکشن",
    tags: "اکشن, ماجراجویی, تاریخی",
    cover: "/images/home1.jpg",
    video: "../video/video1.mp4",
    date: "20-Jan-1997",
  },
  {
    id: 2,
    name: "فیلم جزیره بهشتیی",
    rating: 4.6,
    time: "2hr : 22mins",
    desc: " داستانی مرموزانه و جذاب را در یک دنیای پسا آخرالزمانی با حضور موجوداتی آدم‌خوار روایت می‌کند ",
    starrring: "نیوشا ضیغمی، نیما اکبری",
    genres: "ماجراجویی",
    tags: "ماجراجویی, انیمیشن ,خانوادگی",
    cover: "../images/home2.jpg",
    video: "../video/video2.mp4",
    date: "10-JUL-2021",
  },
  {
    id: 3,
    name: "فیلم دزدان دریایی",
    rating: 4.8,
    time: "2hr : 22mins",
    desc: "مستندی جذاب از عکاسی فوق‌العاده، اما نامرئی که در طول زندگی‌اش، آثار بی‌نظیر وی ناشناخته و چاپ‌نشده باقی‌ ماندند و خیلی از نگاتیوهایش هرگز چاپ نشدند ",
    starrring: "مهران غفوریان, مریمی سعادتی",
    genres: "ماجراجویی",
    tags: "ماجراجویی,اکشن ",
    cover: "../images/home3.jpg",
    video: "../video/video3.mp4",
    date: "20-FEB-2010",
  },
  {
    id: 4,
    name: "فیلم ارباب حلقه ها",
    rating: 4.9,
    time: "2hr : 22mins",
    desc: " بدون تردید سال ۲۰۲۳ یکی از پربارترین سال‌های دنیای انیمه بود، میزان استقبال مخاطبان که به خوبی نشان‌دهنده این مسئله است",
    starrring: "سعید اکبرزاده, غلامرضا عطار",
    genres: "اکشن",
    tags: "اکشن, ماجراجویی, تاریخی",
    cover: "../images/home4.jpg",
    video: "../video/video4.mp4",
    date: "12-Aug-2015",
  },
];
export const upcome = [
  {
    id: 1,
    cover: "../images/upcome/u1.jpg",
    name: "فیلم هابیت ",
    time: "2hr : 38mins",
  },
  {
    id: 2,
    cover: "../images/upcome/u2.jpg",
    name: "فیلم سایه ها",
    time: "2hr : 38mins",
  },
  {
    id: 3,
    cover: "../images/upcome/u3.jpg",
    name: "فیلم باب اسفنجی",
    time: "2hr : 38mins",
  },
  {
    id: 4,
    cover: "../images/upcome/u4.jpg",
    name: "ارتش تک نفره",
    time: "2hr : 38mins",
  },
  {
    id: 5,
    cover: "../images/upcome/u5.jpg",
    name: "فیلم ملکه الیزابت",
    time: "2hr : 38mins",
  },
];
export const latest = [
  {
    id: 1,
    cover: "../images/upcome/u6.png",
    name: "فیلم پادشاه جنگل",
    time: "2hr : 38mins",
  },
  {
    id: 2,
    cover: "../images/upcome/u7.jpg",
    name: "فیلم لوک خوش شانس ",
    time: "2hr : 38mins",
  },
  {
    id: 3,
    cover: "../images/upcome/u1.jpg",
    name: "فیلم عمو پورنگ",
    time: "2hr : 38mins",
  },
  {
    id: 4,
    cover: "../images/upcome/u5.jpg",
    name: "فیلم موش و گربه",
    time: "2hr : 38mins",
  },
  {
    id: 5,
    cover: "../images/upcome/u4.jpg",
    name: "فیلم پلنگ صورتی ",
    time: "2hr : 38mins",
  },
];

export const trending = [
  {
    id: 1,
    name: "فیلم دایناسورها",
    rating: 4.7,
    time: "2hr : 22mins",
    desc: " جوئل و الی، زوجی که از طریق سختی دنیایی که در آن زندگی می‌کنند به هم متصل شده‌اند، مجبور می‌شوند شرایط وحشیانه و قاتلان بی‌رحم را در سفری در سراسر آمریکای پس از همه‌گیری تحمل کنند",
    starrring: "رضا اکبری , مریم حیدری",
    genres: "اکشن",
    tags: "اکشن, ماجراجویی, تاریخی",
    cover: "../images/img/slide1.png",
    date: "20-Jan-1997",
  },
  {
    id: 2,
    name: "امپراطور کبیر",
    rating: 4.6,
    time: "2hr : 22mins",
    desc: "داستان سریال 20 سال پس از نابودی تمدن مدرن می گذرد. جوئل، یک بازمانده سرسخت، استخدام می شود تا الی، یک دختر 14 ساله را از یک منطقه ظالمانه قرنطینه خارج کند. ",
    starrring: "علی رضازاده, عادل فردوسی پور",
    genres: "ماجراجویی",
    tags: "ماجراجویی,انمیشن ,خانوادگی",
    cover: "../images/img/slide2.jpg",
    date: "10-JUL-2021",
  },
  {
    id: 3,
    name: "فیلم ارباب حلقه ها",
    rating: 4.8,
    time: "2hr : 22mins",
    desc: "مادر میکی در کمپ ترک اعتیاد است، پدرش از دنیا رفته، خاله‌اش اعصاب خردکن است و در نیوجرسی به مدرسه جدیدی می‌رود",
    starrring: " جیمز باند, جنیفر لوپز",
    genres: "ماجراجویی",
    tags: "ماجراجویی,اکشن ",
    cover: "../images/img/slide3.jpg",
    date: "20-FEB-2010",
  },
];
export const recommended = [
  {
    id: 4,
    cover: "../images/rec/rec1.jpg",
    name: "ارتش تک نفره",
    time: "2hr : 38mins",
  },
  {
    id: 5,
    cover: "../images/rec/rec2.jpg",
    name: "ملکه الیزابت",
    time: "2hr : 38mins",
  },
  {
    id: 1,
    cover: "../images/rec/rec3.jpg",
    name: "پدر خوانده",
    time: "2hr : 38mins",
  },
  {
    id: 2,
    cover: "../images/rec/rec4.jpg",
    name: "پس از باران",
    time: "2hr : 38mins",
  },
  {
    id: 3,
    cover: "../images/upcome/u3.jpg",
    name: "فیلم شهر قشنگ",
    time: "2hr : 38mins",
  },
];
